version: "2"
services:
        node-jsapp:
                image: "${nodeimg}"
                ports:
                        - 8084:3000
        mysql:
                image: mysql:5.7.39
                container_name: mysql
                hostname: mysql
                environment:
                  MYSQL_ROOT_PASSWORD: mypassword
                  MYSQL_DATABASE: MyDB
                  MYSQL_USER: user
                  MYSQL_PASSWORD: mypassword
                volumes:
                  - /opt/docker/nodeapp/sql-file.sql:/docker-entrypoint-initdb.d/init.sql
                  - /opt/docker/nodeapp/mysql_data:/var/lib/mysql
