---
- name: Deploy Node.js app on Docker host
  hosts: dockerdevhost
  become: true
  tasks:
    - name: Install Docker Module for Python
      pip:
         name: docker
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}:{{ DOCK_TAG }}"
        source: pull
    - name: Creates directory
      file:
       path: /opt/docker/nodeapp
       state: directory
    - name: Copy file to remote host
      copy:
       src: "{{ W_PATH }}"/sql-file.sql
       dest: /opt/docker/nodeapp/sql-file.sql
    - name: Down Docker Compose
      docker_compose:
       project_src: "{{ W_PATH }}"/docker-compose.yml
       state: absent
    - name: Run Docker Compose
      docker_compose:
       project_src: "{{ W_PATH }}"/docker-compose.yml
       state: started
       env:
         dimage: "{{ docker_image_name }}"