---
- name: Deploy Node.js app on Docker host
  hosts: dockerdevhost
  become: true
  tasks:
    - name: Install Docker Module for Python
      pip:
         name: docker
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}:{{ DOCK_TAG }}"
        source: pull
    - name: Creates directory
      file:
       path: /opt/docker/nodeapp
       state: directory
    - name: Copy file to remote host
      copy:
       src: {{ item.src }}
       dest: {{ item.dest }}
      loop: 
        - src: "{{ W_PATH }}/sql-file.sql"
          dest: /opt/docker/nodeapp/sql-file.sql
        - src: "{{ W_PATH }}/docker-compose.yml"
          dest: /opt/docker/nodeapp/docker-compose.yml
    - name: Down Docker Compose
      command: docker-compose down
      args:
       chdir: /opt/docker/nodeapp/
    - name: Down Docker up
      command: docker-compose up -d
      args:
       chdir: /opt/docker/nodeapp/
    