---
- name: Deploy Node.js app on Docker host
  hosts: dockerdevhost
  become: true
  tasks:
    - name: Install python pip
      package:
        name: 
         - python-pip
         - docker-compose
        state: present
    - name: Install Docker Module for Python
      pip:
         name: docker
    - name: Pull Docker image
      docker_image:
        name: "{{ docker_image_name }}:{{ DOCK_TAG }}"
        source: pull

    - name: Stop and remove running container
      docker_container:
        name: "{{ docker_container_name }}"
        state: stopped
        remove: yes

    - name: Run Docker container
      docker_container:
        name: "my-nodeapp"
        image: "{{ docker_image_name }}:{{ DOCK_TAG }}"
        state: started
        restart_policy: always
        ports:
          - "8083:3000"
